baseURL: "in-the-datas-own-words.netlify.app"
languageCode: "en-us"
title: "In the Data's Own Words"
theme: "PaperMod"

params:
  homeInfoParams:
    Title: "Stories the data wants to tell."
    Content: >
      A collection of stories told by asking the data nicely to speak its mind. No torture required.
      Also, I sometimes thought-dump. Those are just in my own words. 
  showBreadcrumbs: true
  socialIcons:
    - name: facebook
      url: "https://facebook.com/"
    - name: twitter
      url: "https://twitter.com/"
    - name: github
      url: "https://github.com/"
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 0
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 3

profileMode:
  enabled: false
  title: TEST


socialIcons:
  - name: x
    title: X (Twitter)
    url: "https://x.com/"
  - name: github
    title: GitHub
    url: "https://github.com/"
